docker run -d \
  --name db1_postgres \
  -e POSTGRES_USER="alex" \
  -e POSTGRES_PASSWORD="root" \
  -e POSTGRES_DB="db1" \
  -v db1_postgres_data:/var/lib/postgresql/data \
  -p 5432:5432 \
  postgres:18
#docker start db1_postgres   to stop run docker stop db1_postgres
#docker stop db1_postgres docker rm db1_postgres

#docker run -d \ -name db1_postgres \ #-e POSTGRES_USER=alex \

#-e POSTGRES_DB=db1 \ #-e POSTGRES_PASSWORD=yourpassword \

#-p 5432:5432 \#postgres